services:
  react_knock:
    container_name: react_knock
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app:cached
    ports:
      - "3000:3000"
    tty: true
    # command: >
    #   /bin/sh -c '
    #   npx create-react-app@latest --ts